# Generated by Django 2.1.5 on 2019-02-08 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Players',
            fields=[
                ('player_id', models.IntegerField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=100)),
                ('nationality', models.CharField(blank=True, max_length=50, null=True)),
                ('batting_style', models.CharField(blank=True, max_length=100, null=True)),
                ('bowling_style', models.CharField(blank=True, max_length=100, null=True)),
                ('speciality', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'players',
                'managed': False,
            },
        ),
    ]
